### ISSUE TITLE
[Help Requested] Fixing Typos in Documentation

### ISSUE THREAD

**Issue by aarondill** [garronej/tsafe#22]
The very start of the `[is](https://docs.tsafe.dev/is)` function's documentation says:
```
is is meant to be used in conjonction with assert and enable you to tell the compiler:
"Trust me this `valule` is of type `T`" or "Trust me this `value` is not of type `T`"
```
This should be:
```
`is` is meant to be used in conjunction with `assert` and enables you to tell the compiler:
"Trust me, this `value` is of type `T`" or "Trust me this `value` is not of type `T`"
```
This is one of a few typos I have noticed, as well as missing commas in the import line on [assert](https://docs.tsafe.dev/assert):
```js
// The website says
import { assert AssertionError } from "tsafe/assert";
// Should say
import { assert, AssertionError } from "tsafe/assert";  
```

If it is possible, I would be happy to submit a pull request to modify these typos, however I cannot seem to find where these files are stored. If that is not a possibility, I can collect all the typos noticed into a single issue, such as this one, for easy reference and fixing.

**Comment by aarondill** [comment]
I found the `docs_v1` branch, which appears to be where the documentation files are stored, but there are many duplicate files, so I'm not sure which files need to be edited and which are auto-generated. A pointer on the workflow of editing the docs page would be greatly appreciated!

**Comment by aarondill** [comment]
@garronej What exactly is the [anegdotal](https://github.com/garronej/tsafe/tree/docs_v1/anegdotal) and [main](https://github.com/garronej/tsafe/tree/docs_v1/main) folders for? It seems that the website lives at the root directory, and if I attempt to navigate to the files in either folder, the site redirects to the root directory.

**Comment by garronej** [comment]
@aarondill,  
They are legacy pages.  
The MD files are generated automatically by GitBook.  
I just sent you an invite by email for if you want to edit directly on GitBook.  

In any case, thank you for your help!
