### ISSUE TITLE
`tsafe` has improper esm exports

### ISSUE THREAD

**Issue by nopeless** [garronej/tsafe#25]
`import { assert } from "tsafe"` does not work in latest versions

Last known working point (is not the bisection point, might be working on later versions): `1.2.1`

@garronej 

If you need minimum repro, let me know

**Comment by garronej** [comment]
Thank you for the report.

**Comment by garronej** [comment]
Fixing asap

**Comment by garronej** [comment]
Hi @nopeless,  
So 1.3 is when I started to release for ESM alongside CJS.  
I though I did everything right but apparently no 😟  
I tried to reproduce in every environement that I know of but I was unable to get any error.  
If you could please give me some more infos, a reproduction repo would be great obviously.  
Thank you for your help!

**Comment by nopeless** [comment]
@garronej thanks for the quick reply. I'll send a repro in a few hours

**Comment by garronej** [comment]
thank you very much !

**Comment by nopeless** [comment]
@garronej 
https://stackblitz.com/edit/github-emokqj?file=test%2Fmain.spec.ts

Here is the reproduction

**Comment by garronej** [comment]
Thank you.  
It's next in my stack

**Comment by nopeless** [comment]
Additional context: it seems that adding `"type": "module"` breaks

**Comment by garronej** [comment]
I'ts not fixed.
I'm going to solve this one and for all

**Comment by garronej** [comment]
Hi @nopeless,  

I'm finally done,  
Gosh releasing in CJS + ESM + Deno + featuring short import path + enabling cherry-picking + having intelissence suggestion when writing `import from "tsafe/*"` is HARD.  
Can't believe I had to write my own bundler for this.  

Anyway, thank you for taking the time to report.  
If you could confirm that it's indeed working with `tsafe: 1.4.2` that'll be great.

**Comment by nopeless** [comment]
Works perfectly!

Great job 👍
