### ISSUE TITLE
Error identifying equality creating z.custom

### ISSUE THREAD

**Issue by sonegobruno** [garronej/tsafe#30]
I encountered a problem identifying equality between types generated by z.custom on an object

General file
![Captura de tela de 2023-11-16 09-19-04](https://github.com/garronej/tsafe/assets/33105540/b59ccd76-6a4c-4bf1-b34a-45a1467910bc)

Schema type inferred
![Captura de tela de 2023-11-16 09-24-56](https://github.com/garronej/tsafe/assets/33105540/eaae426c-0c91-4a1a-9c13-6b1fa1c01392)

Type created
![Captura de tela de 2023-11-16 09-24-59](https://github.com/garronej/tsafe/assets/33105540/8f7bb1a0-5a61-461c-aa6f-8a3d46f44cf9)

It can be seen that when the schema assert is performed directly it passes without problems. However, when asserting within an object it presents an error even though it has the same typing.

I also noticed that when determining the attribute as optional the error disappears.

**Comment by garronej** [comment]
Also, quick tip, I encourage you to use anonymous scope `{}` for testing equality of your types. It makes the core easyer to reason about and enable to reuse the same generic names multiple times in a single file.

**Comment by sonegobruno** [comment]
> Olá@sonegobruno,
> 
> Sim, desculpe, tenho que trabalhar no `Equals`tipo, às vezes dá falso negativo, ainda é melhor aquela falsa igualdade.
> 
> A solução alternativa que implemento quando o tipo Equal é bloqueado é:
> 
> ```ts
> {
>   type Expected = Shema;
>   type Got = z.infer<typeof statusShema>;
> 
>   assert<Expected extends Got ? true : false>();
>   assert<Got extends Expected ? true : false>();
> }
> ```
> 
> Contanto que seus tipos não envolvam função, isso é um bullet poof. Se seus tipos envolvem função, ele pode, em certos casos extremos, gerar falsos positivos (considerando tipos iguais que não são).

Thanks this worked for me 👍

**Comment by garronej** [comment]
Glad the workaround does it for you!
