### ISSUE TITLE
`AssertionError.message` is not the original message

### ISSUE THREAD

**Issue by psychedelicious** [garronej/tsafe#35]
The [docs indicate that `AssertionError.message` should be exactly the original message](https://docs.tsafe.dev/assert#error-thrown), but it is not.

```ts
import { assert, AssertionError } from "tsafe";

try {
  assert(false, "This is my error message");
} catch (e) {
  if (e instanceof AssertionError) {
    // Expected: 'This is my error message'
    // Actual: 'Wrong assertion encountered: "This is my error message"'
    console.log(e.message);
  }
}

try {
  assert(false);
} catch (e) {
  if (e instanceof AssertionError) {
    // Expected: ''
    // Actual: 'Wrong assertion encountered'
    console.log(e.message);
  }
}
```

Demo: https://codesandbox.io/p/sandbox/kyljr8

Code responsible for this behaviour: https://github.com/garronej/tsafe/blob/main/src/assert.ts#L9

I'd prefer for `AssertionError.message` to be the original message, as described in the docs. But changing this might be considered a breaking change - for example, library consumers may match errors against this string. And maybe there is another reason for it to have the extra text.

Maybe the original message could be stored in the error as e.g. `AssertionError.originalMessage`.

Otherwise, it's easy to extract the message:

```ts
function extractMessageFromAssertionError(error: AssertionError): string | null {
  const match = error.message.match(/Wrong assertion encountered: "(.*)"/);
  return match ? (match[1] ?? null) : null;
}
```

**Comment by garronej** [comment]
I see the issue and I agree with you.  

However I'm afraid to break a ton of unit tests by implementing this change.  
If the `originalMessage` solution works for you I'm happy to merge a PR.
